# Generated by Django 5.1.3 on 2024-12-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ProductImage',
        ),
    ]
